export const TOGGLE_CHAT = "TOGGLE_CHAT";
export const TOGGLE_SHOW = "TOGGLE_SHOW";
export const UPDATE_CURRENT_FRIEND = "UPDATE_CURRENT_FRIEND";
export const UPDATE_CURRENT_SEARCH = "UPDATE_CURRENT_SEARCH";
